### ISSUE TITLE
Should jsonschema be a noarch package?

### ISSUE THREAD

**Issue by Lothiraldan** [conda-forge/jsonschema-feedstock#25]
Issue: Jsonschema conda package is arch-dependent while Jsonschema Pypi package is not

<br/>

Upstream jsonschema is an universal wheel https://github.com/Julian/jsonschema/blob/master/setup.cfg#L58.

Should the jsonschema Conda package be a noarch package? I can do the pull-request if yes, just wanted to ask if there is a reason why the conda package is not a noarch package today.

My context is that I'm building a Conda package which depends on jsonschema and it seems jsonschema has not been built for Python 3.8.

**Comment by nehaljwani** [comment]
@jjhelmus What's your take on this? I ask because you had opened a PR for this a while ago.

**Comment by jjhelmus** [comment]
jsonschema still supports Python 2.7 and has a requirement (functools32) that is only needed on Python 2.7.  This precludes the creation of a `noarch: python` conda package.

**Comment by Lothiraldan** [comment]
Its make sense, thank you for your answer.
